-- Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  role text not null check (role in ('admin', 'host', 'app_owner', 'owner')), -- Optional: specific roles constraint
  team_id bigint, -- Will add foreign key later
  created_at timestamptz default now()
);

-- Create Teams Table
-- Note: SQLite REAL budget -> numeric/decimal for money handling in Postgres/Supabase
-- 'bidding_locked' integer (0/1) -> smallint or integer (0 or 1). Keeping integer for compatibility with existing code.
CREATE TABLE IF NOT EXISTS public.teams (
  id bigint generated by default as identity primary key,
  name text unique not null,
  owner_id bigint, -- Will add foreign key later
  owner_name text,
  logo text,
  budget numeric default 1000000, -- Changed to numeric for currency precision
  bidding_locked integer default 0,
  access_code text,
  plain_password text,
  created_at timestamptz default now()
);

-- Create Players Table
CREATE TABLE IF NOT EXISTS public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  image text,
  role text not null,
  country text,
  base_price numeric not null,
  status text default 'AVAILABLE', -- 'AVAILABLE', 'SOLD', 'UNSOLD'
  sold_price numeric,
  sold_to_team bigint,
  was_unsold integer default 0,
  serial_number integer,
  age integer,
  created_at timestamptz default now()
);

-- Create Bids Table
CREATE TABLE IF NOT EXISTS public.bids (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id),
  team_id bigint not null references public.teams(id),
  amount numeric not null,
  timestamp timestamptz default now()
);

-- Create Auction State Table
CREATE TABLE IF NOT EXISTS public.auction_state (
  id bigint primary key, -- Likely just 1 row with ID 1
  status text default 'STOPPED',
  current_player_id bigint,
  bidding_locked integer default 0,
  bid_increment_1 numeric default 500,
  bid_increment_2 numeric default 1000,
  bid_increment_3 numeric default 5000,
  max_players_per_team integer default 10,
  enforce_max_bid integer default 0,
  updated_at timestamptz default now()
);

-- Add Foreign Keys (Separate constraints to avoid dependency errors during creation)
ALTER TABLE public.users ADD CONSTRAINT fk_user_team FOREIGN KEY (team_id) REFERENCES public.teams(id);

-- Initialize Auction State (Idempotent)
INSERT INTO public.auction_state (id, status)
VALUES (1, 'STOPPED')
ON CONFLICT (id) DO NOTHING;

-- Seed Default Users (Passwords will need to be re-hashed if migration implies fresh start, or insert pre-hashed)
-- WARNING: These default passwords need to be hashed by the backend. 
-- For direct SQL insertion, you would need the bcrypt hash.
-- The existing backend code seeds users if they don't exist.
